### PR TITLE
Support Webpack 2.x

### PR DESCRIPTION
**Pull request by ericclemmons**
I tried this plugin out with `webpack beta`. I am getting following error

```
/Volumes/DATA/Bhavin/Projects/temp/webpack_demo/node_modules/enhanced-resolve/lib/Resolver.js:30
		throw new Error("Signature changed: context parameter added");
		^

Error: Signature changed: context parameter added
    at Tapable.resolve (/Volumes/DATA/Bhavin/Projects/temp/webpack_demo/node_modules/enhanced-resolve/lib/Resolver.js:30:9)
    at NormalModuleFactory.<anonymous> (/Volumes/DATA/Bhavin/Projects/temp/webpack_demo/node_modules/npm-install-webpack-plugin/src/plugin.js:24:30)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Volumes/DATA/Bhavin/Projects/temp/webpack_demo/node_modules/tapable/lib/Tapable.js:135:13)
    at NormalModuleFactory.create (/Volumes/DATA/Bhavin/Projects/temp/webpack_demo/node_modules/webpack/lib/NormalModuleFactory.js:158:8)
    at /Volumes/DATA/Bhavin/Projects/temp/webpack_demo/node_modules/webpack/lib/Compilation.js:214:11
    at /Volumes/DATA/Bhavin/Projects/temp/webpack_demo/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Volumes/DATA/Bhavin/Projects/temp/webpack_demo/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Volumes/DATA/Bhavin/Projects/temp/webpack_demo/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/Volumes/DATA/Bhavin/Projects/temp/webpack_demo/node_modules/webpack/lib/Compilation.js:185:8)
    at Compilation.processModuleDependencies (/Volumes/DATA/Bhavin/Projects/temp/webpack_demo/node_modules/webpack/lib/Compilation.js:170:7)
```

It appears to be conflicting with [enhanced-resolve](https://github.com/webpack/enhanced-resolve/blob/master/lib/Resolver.js). Not sure, if this should be fixed here or should enhanced-resolve be more forgiving.

### CODE REVIEW

**Comment by ericclemmons** [comment]
Ok, so the only caveat is that, since my examples are using `npm link`, I have to update `webpack` in the root `package.json` for this to test correctly.

But both Webpack1 & Webpack2 function!

**Comment by satya164** [comment]
Amazing! Will try this out ASAP :D

**Comment by ericclemmons** [comment]
@satya164 I have 2 example folders (`example/webpack1` and `example/webpack2`) which I use for testing locally.

The only caveat is that, since this project gets `npm link`ed, you need to have the correct `webpack` installed in the root.

**Comment by satya164** [comment]
@ericclemmons Okies, will keep this in mind.

**Pull request merged**
